name: CI
on:
  push:
  pull_request:
env:
  JuliaVersion: 1.6.0-beta1
  JULIA_GITHUB_ACTIONS_CI: ON
  JULIA_VULKAN_LIBNAME: "libvk_swiftshader"
jobs:
  ubuntu-latest-x64:
    runs-on: ubuntu-latest
    env:
      VULKAN_SDK: $GITHUB_WORKSPACE/../$VulkanSDKVersion/x86_64
    steps:
    - uses: actions/checkout@v2
    - name: Install xvfb for GLFW
      run: sudo apt-get install xvfb && Xvfb :99 &
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{env.JuliaVersion}}
        arch: x64
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-runtest@latest
      env:
        DISPLAY: :99
    - uses: julia-actions/julia-uploadcodecov@latest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  windows-latest-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{env.JuliaVersion}}
        arch: x64
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-runtest@latest
      env:
        DISPLAY: :99
    - uses: julia-actions/julia-uploadcodecov@latest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  macos-latest-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{env.JuliaVersion}}
        arch: x64
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-runtest@latest
      env:
        DISPLAY: :99
    - uses: julia-actions/julia-uploadcodecov@latest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
